# Generated by Django 4.2.21 on 2025-11-25 03:52

import core.models.allegati
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allegato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="ID Oggetto")),
                (
                    "titolo",
                    models.CharField(
                        help_text="Titolo descrittivo dell'allegato",
                        max_length=255,
                        verbose_name="Titolo",
                    ),
                ),
                (
                    "descrizione",
                    models.TextField(
                        blank=True,
                        help_text="Descrizione dettagliata del contenuto",
                        verbose_name="Descrizione",
                    ),
                ),
                (
                    "tipo_allegato",
                    models.CharField(
                        choices=[
                            ("doc_contratto", "📄 Contratto"),
                            ("doc_fattura", "🧾 Fattura"),
                            ("doc_preventivo", "💰 Preventivo"),
                            ("doc_ordine", "📋 Ordine"),
                            ("doc_bolla", "📦 Bolla Consegna"),
                            ("doc_certificato", "🏆 Certificato"),
                            ("doc_libretto", "📓 Libretto"),
                            ("doc_patente", "🪪 Patente"),
                            ("doc_carta_identita", "🆔 Carta Identità"),
                            ("doc_codice_fiscale", "📊 Codice Fiscale"),
                            ("doc_visura", "📋 Visura"),
                            ("doc_bilancio", "💼 Bilancio"),
                            ("email_inviata", "📧 Email Inviata"),
                            ("email_ricevuta", "📨 Email Ricevuta"),
                            ("sms_inviato", "💬 SMS Inviato"),
                            ("chiamata", "☎️ Chiamata"),
                            ("fax", "📠 Fax"),
                            ("messaggio", "💭 Messaggio"),
                            ("foto_documento", "📷 Foto Documento"),
                            ("foto_generale", "🖼️ Fotografia"),
                            ("video", "🎥 Video"),
                            ("audio", "🎵 Audio"),
                            ("screenshot", "🖥️ Screenshot"),
                            ("nota_interna", "📝 Nota Interna"),
                            ("nota_cliente", "💭 Nota Cliente"),
                            ("promemoria", "⏰ Promemoria"),
                            ("appunto", "✏️ Appunto"),
                            ("verbale", "📄 Verbale"),
                            ("scheda_tecnica", "⚙️ Scheda Tecnica"),
                            ("manuale", "📖 Manuale"),
                            ("report_tecnico", "🔧 Report Tecnico"),
                            ("log_manutenzione", "🛠️ Log Manutenzione"),
                            ("checklist", "✅ Checklist"),
                            ("listino", "💲 Listino Prezzi"),
                            ("catalogo", "📚 Catalogo"),
                            ("brochure", "📰 Brochure"),
                            ("offerta", "🎯 Offerta"),
                            ("polizza", "🛡️ Polizza"),
                            ("denuncia", "⚠️ Denuncia"),
                            ("sentenza", "⚖️ Sentenza"),
                            ("decreto", "📜 Decreto"),
                            ("ricevuta", "🧾 Ricevuta"),
                            ("bonifico", "💳 Bonifico"),
                            ("estratto_conto", "📊 Estratto Conto"),
                            ("link_esterno", "🔗 Link Esterno"),
                            ("backup", "💾 Backup"),
                            ("altro", "📎 Altro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo Allegato",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="File allegato (max 20MB)",
                        null=True,
                        upload_to=core.models.allegati.allegato_upload_path,
                        verbose_name="File",
                    ),
                ),
                (
                    "url_esterno",
                    models.URLField(
                        blank=True,
                        help_text="Link esterno al posto del file",
                        verbose_name="URL Esterno",
                    ),
                ),
                (
                    "contenuto_testo",
                    models.TextField(
                        blank=True,
                        help_text="Contenuto testuale per note e appunti",
                        verbose_name="Contenuto Testo",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Tag separati da virgola per ricerca",
                        max_length=255,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("attivo", "Attivo"),
                            ("archiviato", "Archiviato"),
                            ("scaduto", "Scaduto"),
                            ("eliminato", "Eliminato"),
                        ],
                        default="attivo",
                        max_length=20,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "priorita",
                    models.CharField(
                        choices=[
                            ("bassa", "Bassa"),
                            ("normale", "Normale"),
                            ("alta", "Alta"),
                            ("critica", "Critica"),
                        ],
                        default="normale",
                        max_length=20,
                        verbose_name="Priorità",
                    ),
                ),
                (
                    "data_documento",
                    models.DateField(
                        blank=True,
                        help_text="Data del documento originale",
                        null=True,
                        verbose_name="Data Documento",
                    ),
                ),
                (
                    "data_scadenza",
                    models.DateField(
                        blank=True,
                        help_text="Data di scadenza del documento",
                        null=True,
                        verbose_name="Data Scadenza",
                    ),
                ),
                (
                    "is_pubblico",
                    models.BooleanField(
                        default=True,
                        help_text="Visibile a tutti gli utenti autorizzati",
                        verbose_name="Pubblico",
                    ),
                ),
                (
                    "is_confidenziale",
                    models.BooleanField(
                        default=False,
                        help_text="Visibile solo al creatore e admin",
                        verbose_name="Confidenziale",
                    ),
                ),
                (
                    "dimensione_file",
                    models.PositiveIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Dimensione File (bytes)",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=100,
                        verbose_name="MIME Type",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        verbose_name="Checksum SHA256",
                    ),
                ),
                (
                    "creato_il",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "modificato_il",
                    models.DateTimeField(auto_now=True, verbose_name="Modificato il"),
                ),
                (
                    "versione",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Versione"
                    ),
                ),
                (
                    "allegato_padre",
                    models.ForeignKey(
                        blank=True,
                        help_text="Riferimento alla versione originale",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versioni",
                        to="core.allegato",
                        verbose_name="Allegato Padre",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Tipo Oggetto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allegato",
                "verbose_name_plural": "Allegati",
                "ordering": ["-creato_il"],
                "permissions": [
                    (
                        "view_allegato_confidenziale",
                        "Può visualizzare allegati confidenziali",
                    ),
                    ("manage_all_allegati", "Può gestire tutti gli allegati"),
                    ("download_allegati", "Può scaricare allegati"),
                ],
            },
        ),
    ]
