# Generated by Django 4.2.21 on 2025-11-25 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allegato",
            name="creato_da",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allegati_creati",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creato da",
            ),
        ),
        migrations.AddField(
            model_name="allegato",
            name="modificato_da",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allegati_modificati",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificato da",
            ),
        ),
        migrations.AddIndex(
            model_name="allegato",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="core_allega_content_f28245_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="allegato",
            index=models.Index(
                fields=["tipo_allegato"], name="core_allega_tipo_al_f2c62a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="allegato",
            index=models.Index(fields=["stato"], name="core_allega_stato_02b022_idx"),
        ),
        migrations.AddIndex(
            model_name="allegato",
            index=models.Index(
                fields=["creato_il"], name="core_allega_creato__751be0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="allegato",
            index=models.Index(
                fields=["data_scadenza"], name="core_allega_data_sc_7595c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="allegato",
            index=models.Index(fields=["tags"], name="core_allega_tags_d81b04_idx"),
        ),
    ]
