# Generated by Django 4.2.21 on 2025-11-26 06:46

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promemoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titolo", models.CharField(max_length=200, verbose_name="Titolo")),
                (
                    "descrizione",
                    models.TextField(blank=True, null=True, verbose_name="Descrizione"),
                ),
                (
                    "data_creazione",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "data_scadenza",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data scadenza"
                    ),
                ),
                (
                    "completato",
                    models.BooleanField(default=False, verbose_name="Completato"),
                ),
                (
                    "data_completamento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data completamento"
                    ),
                ),
                (
                    "priorita",
                    models.CharField(
                        choices=[
                            ("bassa", "Bassa"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=10,
                        verbose_name="Priorità",
                    ),
                ),
                (
                    "assegnato_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promemoria_assegnati",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assegnato a",
                    ),
                ),
                (
                    "creato_da",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promemoria_creati",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promemoria",
                "verbose_name_plural": "Promemoria",
                "db_table": "core_promemoria",
                "ordering": ["completato", "data_scadenza"],
            },
        ),
        migrations.CreateModel(
            name="Messaggio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testo", models.TextField(verbose_name="Testo del messaggio")),
                (
                    "data_invio",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data invio"),
                ),
                ("letto", models.BooleanField(default=False, verbose_name="Letto")),
                (
                    "data_lettura",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data lettura"
                    ),
                ),
                (
                    "allegato",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.models.messaggio_allegato_path,
                        verbose_name="Allegato",
                    ),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messaggi_ricevuti",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinatario",
                    ),
                ),
                (
                    "mittente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messaggi_inviati",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mittente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Messaggio",
                "verbose_name_plural": "Messaggi",
                "db_table": "core_messaggio",
                "ordering": ["-data_invio"],
            },
        ),
    ]
