# Generated by Django 4.2.21 on 2025-12-08 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("anagrafica", "0003_alter_fornitore_partita_iva"),
        ("acquisti", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FatturaFornitore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_fattura",
                    models.CharField(
                        help_text="Numero fattura del fornitore", max_length=100
                    ),
                ),
                (
                    "numero_protocollo",
                    models.CharField(
                        blank=True,
                        help_text="Numero protocollo interno (generato automaticamente)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "data_fattura",
                    models.DateField(help_text="Data fattura del fornitore"),
                ),
                (
                    "data_ricezione",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data ricezione in sistema"
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("ATTESA", "In Attesa"),
                            ("RICEVUTA", "Ricevuta"),
                            ("CONTROLLATA", "Controllata"),
                            ("CONTABILIZZATA", "Contabilizzata"),
                            ("PROGRAMMATA", "Programmata"),
                            ("PAGATA", "Pagata"),
                            ("STORNATA", "Stornata"),
                        ],
                        default="ATTESA",
                        help_text="Stato attuale della fattura",
                        max_length=20,
                    ),
                ),
                (
                    "priorita_pagamento",
                    models.CharField(
                        choices=[
                            ("NORMALE", "Normale"),
                            ("ALTA", "Alta"),
                            ("URGENTE", "Urgente"),
                            ("CRITICA", "Critica"),
                        ],
                        default="NORMALE",
                        help_text="Priorità di pagamento",
                        max_length=20,
                    ),
                ),
                (
                    "importo_netto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Importo netto fattura",
                        max_digits=12,
                    ),
                ),
                (
                    "importo_iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Importo IVA",
                        max_digits=12,
                    ),
                ),
                (
                    "importo_totale",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Importo totale fattura",
                        max_digits=12,
                    ),
                ),
                (
                    "valuta",
                    models.CharField(
                        default="EUR", help_text="Valuta fattura", max_length=3
                    ),
                ),
                (
                    "differenza_importo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Differenza rispetto all'ordine di acquisto",
                        max_digits=12,
                    ),
                ),
                (
                    "note_controllo",
                    models.TextField(
                        blank=True, help_text="Note del controllo fattura"
                    ),
                ),
                (
                    "data_controllo",
                    models.DateTimeField(
                        blank=True, help_text="Data controllo fattura", null=True
                    ),
                ),
                (
                    "data_scadenza",
                    models.DateField(help_text="Data scadenza pagamento"),
                ),
                (
                    "termini_pagamento",
                    models.CharField(
                        help_text="Termini di pagamento (es: 30gg DFFM)", max_length=200
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, help_text="Data effettiva pagamento", null=True
                    ),
                ),
                (
                    "importo_pagato",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Importo effettivamente pagato",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "modalita_pagamento",
                    models.CharField(
                        blank=True,
                        help_text="Modalità di pagamento utilizzata",
                        max_length=100,
                    ),
                ),
                (
                    "file_fattura",
                    models.FileField(
                        blank=True,
                        help_text="File fattura (PDF, immagine, etc.)",
                        null=True,
                        upload_to="fatturazione/fatture/%Y/%m/",
                    ),
                ),
                (
                    "oggetto",
                    models.CharField(
                        blank=True,
                        help_text="Oggetto/descrizione fattura",
                        max_length=500,
                    ),
                ),
                (
                    "note_interne",
                    models.TextField(
                        blank=True, help_text="Note interne non visibili al fornitore"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_ricezione_documento",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data ricezione documento fisico",
                        null=True,
                    ),
                ),
                (
                    "data_contabilizzazione",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data registrazione in contabilità",
                        null=True,
                    ),
                ),
                (
                    "data_programmazione",
                    models.DateTimeField(
                        blank=True, help_text="Data programmazione pagamento", null=True
                    ),
                ),
                (
                    "controllata_da",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utente che ha controllato la fattura",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fatture_controllate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creata_da",
                    models.ForeignKey(
                        help_text="Utente che ha creato la fattura",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fatture_create",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fornitore",
                    models.ForeignKey(
                        help_text="Fornitore della fattura",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="anagrafica.fornitore",
                    ),
                ),
                (
                    "modificata_da",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ultimo utente che ha modificato",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fatture_modificate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ordine_acquisto",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ordine di acquisto di riferimento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="acquisti.ordineacquisto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fattura Fornitore",
                "verbose_name_plural": "Fatture Fornitori",
                "ordering": ["-data_fattura", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScadenzaPagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_scadenza",
                    models.DateField(help_text="Data scadenza pagamento"),
                ),
                (
                    "importo_scadenza",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Importo della scadenza",
                        max_digits=12,
                    ),
                ),
                (
                    "priorita",
                    models.IntegerField(
                        choices=[
                            (1, "Molto Bassa"),
                            (2, "Bassa"),
                            (3, "Normale"),
                            (4, "Alta"),
                            (5, "Molto Alta"),
                        ],
                        default=3,
                        help_text="Priorità pagamento",
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("PIANIFICATA", "Pianificata"),
                            ("IN_PAGAMENTO", "In Pagamento"),
                            ("PAGATA", "Pagata"),
                            ("SCADUTA", "Scaduta"),
                            ("RIMANDATA", "Rimandata"),
                        ],
                        default="PIANIFICATA",
                        max_length=20,
                    ),
                ),
                (
                    "note_pagamento",
                    models.TextField(blank=True, help_text="Note sul pagamento"),
                ),
                (
                    "promemoria_giorni",
                    models.IntegerField(
                        default=3, help_text="Giorni prima per promemoria"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creata_da",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fattura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scadenze",
                        to="fatturazione.fatturafornitore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scadenza Pagamento",
                "verbose_name_plural": "Scadenze Pagamento",
                "ordering": ["data_scadenza", "-priorita"],
            },
        ),
        migrations.CreateModel(
            name="DettaglioFattura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descrizione",
                    models.CharField(
                        help_text="Descrizione della riga fattura", max_length=500
                    ),
                ),
                (
                    "quantita",
                    models.DecimalField(
                        decimal_places=2, help_text="Quantità fatturata", max_digits=10
                    ),
                ),
                (
                    "unita_misura",
                    models.CharField(
                        blank=True,
                        help_text="Unità di misura (pz, kg, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "prezzo_unitario",
                    models.DecimalField(
                        decimal_places=2, help_text="Prezzo unitario", max_digits=10
                    ),
                ),
                (
                    "sconto_percentuale",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sconto percentuale",
                        max_digits=5,
                    ),
                ),
                (
                    "importo_riga",
                    models.DecimalField(
                        decimal_places=2, help_text="Importo totale riga", max_digits=10
                    ),
                ),
                (
                    "aliquota_iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=22.0,
                        help_text="Aliquota IVA percentuale",
                        max_digits=5,
                    ),
                ),
                (
                    "note_riga",
                    models.TextField(
                        blank=True, help_text="Note specifiche della riga"
                    ),
                ),
                (
                    "ordine",
                    models.IntegerField(
                        default=0, help_text="Ordine di visualizzazione"
                    ),
                ),
                (
                    "fattura",
                    models.ForeignKey(
                        help_text="Fattura di appartenenza",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dettagli",
                        to="fatturazione.fatturafornitore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dettaglio Fattura",
                "verbose_name_plural": "Dettagli Fattura",
                "ordering": ["ordine", "id"],
            },
        ),
        migrations.CreateModel(
            name="ComunicazioneFatturato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_comunicazione",
                    models.CharField(
                        choices=[
                            ("RICHIESTA", "Richiesta Fattura"),
                            ("SOLLECITO", "Sollecito"),
                            ("CHIARIMENTO", "Richiesta Chiarimenti"),
                            ("CONFERMA", "Conferma Ricezione"),
                            ("PAGAMENTO", "Avviso Pagamento"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "oggetto",
                    models.CharField(help_text="Oggetto comunicazione", max_length=200),
                ),
                ("messaggio", models.TextField(help_text="Contenuto messaggio")),
                ("email_inviata", models.BooleanField(default=False)),
                ("data_invio", models.DateTimeField(blank=True, null=True)),
                (
                    "email_destinatario",
                    models.EmailField(help_text="Email destinatario", max_length=254),
                ),
                ("risposta_ricevuta", models.BooleanField(default=False)),
                ("data_risposta", models.DateTimeField(blank=True, null=True)),
                (
                    "contenuto_risposta",
                    models.TextField(
                        blank=True, help_text="Contenuto risposta ricevuta"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creata_da",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fattura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comunicazioni",
                        to="fatturazione.fatturafornitore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comunicazione Fatturato",
                "verbose_name_plural": "Comunicazioni Fatturato",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="fatturafornitore",
            index=models.Index(
                fields=["numero_protocollo"], name="fatturazion_numero__fcd7fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fatturafornitore",
            index=models.Index(
                fields=["fornitore", "stato"], name="fatturazion_fornito_e23532_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fatturafornitore",
            index=models.Index(fields=["stato"], name="fatturazion_stato_848100_idx"),
        ),
        migrations.AddIndex(
            model_name="fatturafornitore",
            index=models.Index(
                fields=["data_scadenza"], name="fatturazion_data_sc_1a0dfa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fatturafornitore",
            index=models.Index(
                fields=["data_fattura"], name="fatturazion_data_fa_d75e52_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fatturafornitore",
            unique_together={("fornitore", "numero_fattura", "data_fattura")},
        ),
    ]
