# Generated by Django 4.2.21 on 2025-12-09 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("acquisti", "0001_initial"),
        ("fatturazione", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fatturafornitore",
            name="ordini_acquisto",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ordini di acquisto collegati a questa fattura",
                related_name="fatture_collegate",
                to="acquisti.ordineacquisto",
            ),
        ),
        migrations.AlterField(
            model_name="fatturafornitore",
            name="ordine_acquisto",
            field=models.ForeignKey(
                blank=True,
                help_text="Ordine di acquisto principale di riferimento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="acquisti.ordineacquisto",
            ),
        ),
    ]
