# Generated by Django 4.2.21 on 2025-12-10 03:00

import automezzi.models
import core.mixins.allegati
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("anagrafica", "0003_alter_fornitore_partita_iva"),
    ]

    operations = [
        migrations.CreateModel(
            name="Automezzo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_mezzo",
                    models.IntegerField(
                        blank=True,
                        help_text="Numero identificativo del mezzo",
                        null=True,
                    ),
                ),
                ("targa", models.CharField(max_length=10, unique=True)),
                ("marca", models.CharField(max_length=50)),
                ("modello", models.CharField(max_length=50)),
                ("anno_immatricolazione", models.PositiveIntegerField()),
                ("chilometri_attuali", models.PositiveIntegerField(default=0)),
                ("attivo", models.BooleanField(default=True)),
                ("disponibile", models.BooleanField(default=True)),
                ("bloccata", models.BooleanField(default=False)),
                ("motivo_blocco", models.TextField(blank=True, null=True)),
                (
                    "libretto_fronte",
                    models.FileField(
                        blank=True,
                        help_text="Fronte del libretto di circolazione",
                        null=True,
                        upload_to=automezzi.models.libretto_upload_path,
                    ),
                ),
                (
                    "libretto_retro",
                    models.FileField(
                        blank=True,
                        help_text="Retro del libretto di circolazione",
                        null=True,
                        upload_to=automezzi.models.libretto_upload_path,
                    ),
                ),
                (
                    "assicurazione",
                    models.FileField(
                        blank=True,
                        help_text="File della polizza assicurativa",
                        null=True,
                        upload_to=automezzi.models.assicurazione_upload_path,
                    ),
                ),
                (
                    "data_revisione",
                    models.DateField(
                        blank=True, help_text="Data ultima revisione", null=True
                    ),
                ),
                (
                    "assegnato_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automezzi_assegnati",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(core.mixins.allegati.AllegatiMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CategoriaSpesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("descrizione", models.TextField(blank=True)),
                (
                    "codice",
                    models.CharField(
                        help_text="Codice per export contabili",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("attiva", models.BooleanField(default=True)),
                (
                    "categoria_padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automezzi.categoriaspesa",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categorie Spesa",
            },
        ),
        migrations.CreateModel(
            name="InterventoManutenzione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_programmata", models.DateField()),
                ("data_inizio", models.DateField(blank=True, null=True)),
                ("data_completamento", models.DateField(blank=True, null=True)),
                (
                    "km_programmati",
                    models.PositiveIntegerField(
                        help_text="Km automezzo quando programmato"
                    ),
                ),
                (
                    "km_effettivi",
                    models.PositiveIntegerField(
                        blank=True, help_text="Km effettivi al completamento", null=True
                    ),
                ),
                ("descrizione_dettagliata", models.TextField()),
                (
                    "priorita",
                    models.CharField(
                        choices=[
                            ("bassa", "Bassa"),
                            ("normale", "Normale"),
                            ("alta", "Alta"),
                            ("critica", "Critica"),
                        ],
                        default="normale",
                        max_length=10,
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("programmato", "Programmato"),
                            ("in_corso", "In corso"),
                            ("sospeso", "Sospeso"),
                            ("completato", "Completato"),
                            ("annullato", "Annullato"),
                        ],
                        default="programmato",
                        max_length=15,
                    ),
                ),
                ("officina", models.CharField(blank=True, max_length=100)),
                (
                    "tempo_previsto_ore",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "tempo_effettivo_ore",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "costo_previsto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "costo_manodopera",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "costo_ricambi",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "costo_extra",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "allegati",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=automezzi.models.intervento_upload_path,
                    ),
                ),
                ("note_tecniche", models.TextField(blank=True)),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                ("data_ultima_modifica", models.DateTimeField(auto_now=True)),
                (
                    "automezzo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventi_manutenzione",
                        to="automezzi.automezzo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Interventi Manutenzione",
                "ordering": ["-data_programmata"],
            },
        ),
        migrations.CreateModel(
            name="Ricambio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice_ricambio", models.CharField(max_length=50, unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("descrizione", models.TextField(blank=True)),
                ("categoria", models.CharField(max_length=50)),
                (
                    "marca_compatibile",
                    models.CharField(
                        blank=True, help_text="Marca veicolo compatibile", max_length=50
                    ),
                ),
                ("modello_compatibile", models.CharField(blank=True, max_length=50)),
                (
                    "prezzo_listino",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("fornitore_principale", models.CharField(blank=True, max_length=100)),
                ("scorta_minima", models.PositiveIntegerField(default=0)),
                ("scorta_attuale", models.PositiveIntegerField(default=0)),
                ("attivo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipologiaIntervento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descrizione", models.TextField(blank=True)),
                (
                    "frequenza_consigliata",
                    models.CharField(
                        choices=[
                            ("una_tantum", "Una tantum"),
                            ("giornaliera", "Giornaliera"),
                            ("settimanale", "Settimanale"),
                            ("mensile", "Mensile"),
                            ("trimestrale", "Trimestrale"),
                            ("semestrale", "Semestrale"),
                            ("annuale", "Annuale"),
                            ("per_chilometri", "Per chilometri"),
                            ("ordinario", "Intervento Ordinario"),
                            ("straordinario", "Intervento Straordinario"),
                        ],
                        default="una_tantum",
                        max_length=20,
                    ),
                ),
                (
                    "km_intervallo",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Intervallo in km se frequenza per_chilometri",
                        null=True,
                    ),
                ),
                (
                    "costo_medio_previsto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "tempo_medio_ore",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "critico",
                    models.BooleanField(
                        default=False, help_text="Intervento critico per sicurezza"
                    ),
                ),
                ("attivo", models.BooleanField(default=True)),
                (
                    "categoria_spesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automezzi.categoriaspesa",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tipologie Intervento",
            },
        ),
        migrations.CreateModel(
            name="StatisticheConsumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inizio_periodo", models.DateField()),
                ("data_fine_periodo", models.DateField()),
                ("numero_viaggi", models.PositiveIntegerField(default=0)),
                ("km_totali_periodo", models.PositiveIntegerField(default=0)),
                (
                    "litri_totali_periodo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "costo_totale_periodo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "consumo_medio_100km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "costo_medio_per_km",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "media_litri_per_viaggio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "media_km_per_viaggio",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "miglior_consumo_100km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "peggior_consumo_100km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("data_calcolo", models.DateTimeField(auto_now=True)),
                (
                    "automezzo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistiche_consumo",
                        to="automezzi.automezzo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Statistiche Consumo Aggregate",
            },
        ),
        migrations.CreateModel(
            name="SpesaViaggio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_spesa", models.DateField()),
                (
                    "tipo_spesa",
                    models.CharField(
                        choices=[
                            ("carburante", "Carburante"),
                            ("pedaggi", "Pedaggi autostradali"),
                            ("parcheggi", "Parcheggi"),
                            ("lavaggio", "Lavaggio auto"),
                            ("vitto", "Vitto e alloggio"),
                            ("multe", "Multe e sanzioni"),
                            ("riparazioni", "Riparazioni urgenti"),
                            ("altro", "Altro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("importo", models.DecimalField(decimal_places=2, max_digits=8)),
                ("descrizione", models.CharField(max_length=200)),
                ("note", models.TextField(blank=True)),
                (
                    "luogo",
                    models.CharField(
                        blank=True,
                        help_text="Città/località della spesa",
                        max_length=100,
                    ),
                ),
                (
                    "km_automezzo",
                    models.PositiveIntegerField(
                        help_text="Chilometri al momento della spesa"
                    ),
                ),
                (
                    "scontrino",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=automezzi.models.spesa_viaggio_upload_path,
                    ),
                ),
                ("rimborsabile", models.BooleanField(default=True)),
                ("rimborsata", models.BooleanField(default=False)),
                ("data_rimborso", models.DateField(blank=True, null=True)),
                ("data_inserimento", models.DateTimeField(auto_now_add=True)),
                ("data_modifica", models.DateTimeField(auto_now=True)),
                (
                    "automezzo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spese_viaggio",
                        to="automezzi.automezzo",
                    ),
                ),
                (
                    "categoria_spesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automezzi.categoriaspesa",
                    ),
                ),
                (
                    "dipendente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Spese Viaggio",
                "ordering": ["-data_spesa"],
            },
        ),
        migrations.CreateModel(
            name="Rifornimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("litri", models.DecimalField(decimal_places=2, max_digits=6)),
                ("costo_totale", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "chilometri",
                    models.PositiveIntegerField(
                        help_text="Chilometraggio al momento del rifornimento"
                    ),
                ),
                (
                    "scontrino",
                    models.FileField(
                        blank=True,
                        help_text="Foto dello scontrino del rifornimento",
                        null=True,
                        upload_to=automezzi.models.scontrino_upload_path,
                    ),
                ),
                (
                    "automezzo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rifornimenti",
                        to="automezzi.automezzo",
                    ),
                ),
            ],
            bases=(core.mixins.allegati.AllegatiMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RicambioUsato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantita", models.PositiveIntegerField(default=1)),
                (
                    "prezzo_unitario",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "intervento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ricambi_usati",
                        to="automezzi.interventomanutenzione",
                    ),
                ),
                (
                    "ricambio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automezzi.ricambio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manutenzione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_apertura",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e ora di apertura della manutenzione",
                        null=True,
                    ),
                ),
                (
                    "data_prevista",
                    models.DateField(
                        help_text="Data prevista per l'intervento di manutenzione",
                        null=True,
                    ),
                ),
                ("descrizione", models.CharField(max_length=255)),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("aperta", "Manutenzione Aperta"),
                            ("in_corso", "In Corso"),
                            ("terminata", "Terminata"),
                        ],
                        default="aperta",
                        help_text="Stato della manutenzione",
                        max_length=10,
                    ),
                ),
                (
                    "luogo",
                    models.CharField(
                        blank=True,
                        help_text="Luogo dove viene eseguita la manutenzione",
                        max_length=200,
                    ),
                ),
                (
                    "costo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Costo della manutenzione (da compilare al termine)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "allegati",
                    models.FileField(
                        blank=True,
                        help_text="Allegati della manutenzione (fatture, ricevute ecc.)",
                        null=True,
                        upload_to=automezzi.models.allegati_manutenzione_path,
                    ),
                ),
                (
                    "data_inizio_manutenzione",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e ora di inizio della manutenzione (impostata quando il responsabile compila il form)",
                        null=True,
                    ),
                ),
                (
                    "foglio_accettazione",
                    models.FileField(
                        blank=True,
                        help_text="Foglio di accettazione firmato dall'officina",
                        null=True,
                        upload_to=automezzi.models.allegati_manutenzione_path,
                    ),
                ),
                (
                    "note_responsabile",
                    models.TextField(
                        blank=True,
                        help_text="Note del responsabile (nome addetto, dettagli consegna, ecc.)",
                    ),
                ),
                (
                    "note_finali",
                    models.TextField(
                        blank=True,
                        help_text="Note finali sulla manutenzione completata",
                    ),
                ),
                (
                    "fattura_fornitore",
                    models.FileField(
                        blank=True,
                        help_text="Fattura del fornitore per la manutenzione",
                        null=True,
                        upload_to=automezzi.models.allegati_manutenzione_path,
                    ),
                ),
                (
                    "data_completamento",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e ora di completamento della manutenzione",
                        null=True,
                    ),
                ),
                (
                    "completata",
                    models.BooleanField(
                        default=False, help_text="[DEPRECATO] Usa il campo 'stato'"
                    ),
                ),
                (
                    "automezzo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manutenzioni",
                        to="automezzi.automezzo",
                    ),
                ),
                (
                    "fornitore",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fornitore/Officina che esegue la manutenzione",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="anagrafica.fornitore",
                    ),
                ),
                (
                    "responsabile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Responsabile dell'esecuzione della manutenzione",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manutenzioni_responsabile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seguito_da",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utente che ha aperto e segue la pratica di manutenzione",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manutenzioni_seguite",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(core.mixins.allegati.AllegatiMixin, models.Model),
        ),
        migrations.AddField(
            model_name="interventomanutenzione",
            name="manutenzione_base",
            field=models.OneToOneField(
                blank=True,
                help_text="Collegamento a record manutenzione base esistente",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="automezzi.manutenzione",
            ),
        ),
        migrations.AddField(
            model_name="interventomanutenzione",
            name="responsabile_tecnico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interventi_responsabile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interventomanutenzione",
            name="tipologia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="automezzi.tipologiaintervento",
            ),
        ),
        migrations.CreateModel(
            name="EventoAutomezzo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("incidente", "Incidente"),
                            ("furto", "Furto"),
                            ("fermo", "Fermo amministrativo"),
                            ("guasto", "Guasto/avaria"),
                            ("altro", "Altro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_evento", models.DateField()),
                ("descrizione", models.TextField(blank=True)),
                (
                    "costo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "file_allegato",
                    models.FileField(
                        blank=True,
                        help_text="Foto, verbali, documenti relativi all'evento",
                        null=True,
                        upload_to=automezzi.models.allegato_evento_path,
                    ),
                ),
                ("risolto", models.BooleanField(default=False)),
                (
                    "automezzo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventi",
                        to="automezzi.automezzo",
                    ),
                ),
                (
                    "dipendente_coinvolto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventi_coinvolto",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(core.mixins.allegati.AllegatiMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ControlloAutomezzo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_controllo",
                    models.CharField(
                        choices=[
                            ("settimanale", "Controllo settimanale"),
                            ("mensile", "Controllo mensile"),
                            ("pre_viaggio", "Controllo pre-viaggio"),
                            ("post_viaggio", "Controllo post-viaggio"),
                            ("straordinario", "Controllo straordinario"),
                            ("ispettivo", "Ispezione"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_controllo", models.DateField()),
                ("km_controllo", models.PositiveIntegerField()),
                (
                    "controllo_freni",
                    models.CharField(
                        choices=[
                            ("ok", "OK - Nessun problema"),
                            ("attenzione", "Attenzione - Controllo necessario"),
                            ("intervento", "Intervento richiesto"),
                            ("fermo", "Fermo macchina"),
                        ],
                        default="ok",
                        max_length=10,
                    ),
                ),
                (
                    "controllo_pneumatici",
                    models.CharField(
                        choices=[
                            ("ok", "OK - Nessun problema"),
                            ("attenzione", "Attenzione - Controllo necessario"),
                            ("intervento", "Intervento richiesto"),
                            ("fermo", "Fermo macchina"),
                        ],
                        default="ok",
                        max_length=10,
                    ),
                ),
                (
                    "controllo_luci",
                    models.CharField(
                        choices=[
                            ("ok", "OK - Nessun problema"),
                            ("attenzione", "Attenzione - Controllo necessario"),
                            ("intervento", "Intervento richiesto"),
                            ("fermo", "Fermo macchina"),
                        ],
                        default="ok",
                        max_length=10,
                    ),
                ),
                (
                    "controllo_fluidi",
                    models.CharField(
                        choices=[
                            ("ok", "OK - Nessun problema"),
                            ("attenzione", "Attenzione - Controllo necessario"),
                            ("intervento", "Intervento richiesto"),
                            ("fermo", "Fermo macchina"),
                        ],
                        default="ok",
                        max_length=10,
                    ),
                ),
                (
                    "controllo_carrozzeria",
                    models.CharField(
                        choices=[
                            ("ok", "OK - Nessun problema"),
                            ("attenzione", "Attenzione - Controllo necessario"),
                            ("intervento", "Intervento richiesto"),
                            ("fermo", "Fermo macchina"),
                        ],
                        default="ok",
                        max_length=10,
                    ),
                ),
                (
                    "controllo_interni",
                    models.CharField(
                        choices=[
                            ("ok", "OK - Nessun problema"),
                            ("attenzione", "Attenzione - Controllo necessario"),
                            ("intervento", "Intervento richiesto"),
                            ("fermo", "Fermo macchina"),
                        ],
                        default="ok",
                        max_length=10,
                    ),
                ),
                (
                    "esito_generale",
                    models.CharField(
                        choices=[
                            ("ok", "OK - Nessun problema"),
                            ("attenzione", "Attenzione - Controllo necessario"),
                            ("intervento", "Intervento richiesto"),
                            ("fermo", "Fermo macchina"),
                        ],
                        default="ok",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "azioni_richieste",
                    models.TextField(blank=True, help_text="Azioni da intraprendere"),
                ),
                (
                    "foto_allegati",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=automezzi.models.controllo_upload_path,
                    ),
                ),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                (
                    "automezzo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controlli",
                        to="automezzi.automezzo",
                    ),
                ),
                (
                    "controllore",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Controlli Automezzo",
                "ordering": ["-data_controllo"],
            },
        ),
        migrations.CreateModel(
            name="AllegatoManutenzione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome descrittivo dell'allegato", max_length=200
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="File allegato",
                        upload_to=automezzi.models.allegati_manutenzione_path,
                    ),
                ),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "caricato_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manutenzione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allegati_aggiuntivi",
                        to="automezzi.manutenzione",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allegato Manutenzione",
                "verbose_name_plural": "Allegati Manutenzione",
                "ordering": ["-data_upload"],
            },
        ),
        migrations.CreateModel(
            name="StatisticheCosto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anno", models.PositiveIntegerField()),
                (
                    "trimestre",
                    models.PositiveIntegerField(
                        blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True
                    ),
                ),
                (
                    "costo_carburante",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "costo_manutenzioni",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "costo_spese_viaggio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "costo_interventi",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "costo_documenti",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Assicurazioni, bolli, revisioni",
                        max_digits=10,
                    ),
                ),
                (
                    "costo_eventi",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Multe, incidenti, ecc",
                        max_digits=10,
                    ),
                ),
                (
                    "costo_totale",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("km_percorsi", models.PositiveIntegerField(default=0)),
                (
                    "costo_per_km",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("data_calcolo", models.DateTimeField(auto_now=True)),
                (
                    "automezzo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistiche_costo",
                        to="automezzi.automezzo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Statistiche Costo",
                "unique_together": {("automezzo", "anno", "trimestre")},
            },
        ),
    ]
