# Generated by Django 5.0.8 on 2025-11-30 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafica", "0003_alter_fornitore_partita_iva"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FornitorePreventivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_inviata", models.BooleanField(default=False)),
                ("data_invio", models.DateTimeField(blank=True, null=True)),
                ("email_letta", models.BooleanField(default=False)),
                ("data_lettura", models.DateTimeField(blank=True, null=True)),
                ("ha_risposto", models.BooleanField(default=False)),
                ("data_risposta", models.DateTimeField(blank=True, null=True)),
                (
                    "note_fornitore",
                    models.TextField(blank=True, help_text="Note dal fornitore"),
                ),
                ("numero_solleciti", models.IntegerField(default=0)),
                ("data_ultimo_sollecito", models.DateTimeField(blank=True, null=True)),
                ("token_accesso", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fornitore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anagrafica.fornitore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fornitore Preventivo",
                "verbose_name_plural": "Fornitori Preventivi",
            },
        ),
        migrations.CreateModel(
            name="Preventivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_preventivo_fornitore",
                    models.CharField(
                        help_text="Numero del preventivo assegnato dal fornitore",
                        max_length=100,
                    ),
                ),
                (
                    "importo_totale",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Importo totale del preventivo",
                        max_digits=15,
                    ),
                ),
                ("valuta", models.CharField(default="EUR", max_length=3)),
                (
                    "validita_giorni",
                    models.IntegerField(help_text="Giorni di validità dell'offerta"),
                ),
                (
                    "termini_pagamento",
                    models.CharField(help_text="Es: 30gg DFFM", max_length=200),
                ),
                (
                    "tempi_consegna",
                    models.CharField(
                        help_text="Es: 15 giorni lavorativi", max_length=200
                    ),
                ),
                ("condizioni_trasporto", models.CharField(blank=True, max_length=200)),
                ("garanzia", models.CharField(blank=True, max_length=200)),
                ("note_tecniche", models.TextField(blank=True)),
                ("note_commerciali", models.TextField(blank=True)),
                (
                    "ordine_acquisto_numero",
                    models.CharField(
                        blank=True,
                        help_text="Numero ordine di acquisto generato da questo preventivo",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("data_ricevimento", models.DateTimeField(auto_now_add=True)),
                (
                    "data_scadenza_offerta",
                    models.DateField(
                        help_text="Calcolato automaticamente da validità giorni"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fornitore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="anagrafica.fornitore",
                    ),
                ),
                (
                    "operatore_inserimento",
                    models.ForeignKey(
                        help_text="Operatore che ha inserito il preventivo",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preventivo",
                "verbose_name_plural": "Preventivi",
                "ordering": ["-data_ricevimento"],
            },
        ),
        migrations.CreateModel(
            name="ParametroValutazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descrizione",
                    models.CharField(
                        help_text="Descrizione del parametro (es: Tempo consegna)",
                        max_length=200,
                    ),
                ),
                (
                    "valore",
                    models.CharField(
                        help_text="Valore alfanumerico (es: 15 giorni, Eccellente, €1200)",
                        max_length=100,
                    ),
                ),
                (
                    "ordine",
                    models.IntegerField(
                        default=0, help_text="Ordine di visualizzazione"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creato_da",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preventivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parametri",
                        to="preventivi.preventivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parametro Valutazione",
                "verbose_name_plural": "Parametri Valutazione",
                "ordering": ["ordine", "descrizione"],
            },
        ),
        migrations.CreateModel(
            name="RichiestaPreventivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Numero univoco preventivo",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "titolo",
                    models.CharField(
                        help_text="Titolo/oggetto della richiesta", max_length=200
                    ),
                ),
                (
                    "descrizione",
                    models.TextField(
                        help_text="Descrizione dettagliata del preventivo richiesto"
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("BOZZA", "Bozza"),
                            ("INVIATO_FORNITORI", "Inviato ai fornitori"),
                            ("PREVENTIVI_RACCOLTI", "Preventivi raccolti"),
                            ("IN_VALUTAZIONE", "In valutazione"),
                            ("APPROVATO", "Approvato"),
                            ("ANNULLATO", "Annullato"),
                        ],
                        default="BOZZA",
                        max_length=25,
                    ),
                ),
                (
                    "priorita",
                    models.CharField(
                        choices=[
                            ("BASSA", "Bassa"),
                            ("NORMALE", "Normale"),
                            ("ALTA", "Alta"),
                            ("URGENTE", "Urgente"),
                        ],
                        default="NORMALE",
                        max_length=20,
                    ),
                ),
                ("data_richiesta", models.DateTimeField(auto_now_add=True)),
                (
                    "data_scadenza",
                    models.DateField(help_text="Scadenza per ricevere i preventivi"),
                ),
                (
                    "data_invio_fornitori",
                    models.DateTimeField(
                        blank=True, help_text="Quando inviata ai fornitori", null=True
                    ),
                ),
                (
                    "data_raccolta_completata",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando tutti i preventivi sono stati caricati",
                        null=True,
                    ),
                ),
                (
                    "data_valutazione",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando iniziata la valutazione",
                        null=True,
                    ),
                ),
                ("data_approvazione", models.DateTimeField(blank=True, null=True)),
                (
                    "budget_massimo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Budget massimo disponibile",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("valuta", models.CharField(default="EUR", max_length=3)),
                (
                    "note_interne",
                    models.TextField(
                        blank=True, help_text="Note interne non visibili ai fornitori"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approvatore",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chi deve approvare il preventivo finale",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preventivi_approvati",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fornitori",
                    models.ManyToManyField(
                        related_name="preventivi",
                        through="preventivi.FornitorePreventivo",
                        to="anagrafica.fornitore",
                    ),
                ),
                (
                    "operatore",
                    models.ForeignKey(
                        blank=True,
                        help_text="Operatore che gestisce i preventivi ricevuti",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preventivi_gestiti",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preventivo_approvato",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preventivo scelto dopo approvazione",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="richieste_vinte",
                        to="preventivi.preventivo",
                    ),
                ),
                (
                    "richiedente",
                    models.ForeignKey(
                        help_text="Buyer che ha richiesto il preventivo",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preventivi_richiesti",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Richiesta Preventivo",
                "verbose_name_plural": "Richieste Preventivi",
                "ordering": ["-data_richiesta"],
            },
        ),
        migrations.AddField(
            model_name="preventivo",
            name="richiesta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="preventivi.richiestapreventivo",
            ),
        ),
        migrations.AddField(
            model_name="fornitorepreventivo",
            name="richiesta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="preventivi.richiestapreventivo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="preventivo",
            unique_together={("richiesta", "fornitore")},
        ),
        migrations.AlterUniqueTogether(
            name="fornitorepreventivo",
            unique_together={("richiesta", "fornitore")},
        ),
    ]
