# Generated by Django 5.0.8 on 2025-12-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preventivi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preventivo",
            name="file_preventivo",
            field=models.FileField(
                blank=True,
                help_text="File del preventivo ricevuto dal fornitore (PDF, DOC, etc.)",
                null=True,
                upload_to="preventivi/files/",
            ),
        ),
    ]
