# Generated by Django 4.2.21 on 2025-12-11 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("preventivi", "0002_preventivo_file_preventivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="richiestapreventivo",
            name="auto_attach_documents",
            field=models.BooleanField(
                default=True,
                help_text="Se attivo, i documenti vengono allegati automaticamente al target quando il record viene salvato",
                verbose_name="Allega Documenti Automaticamente",
            ),
        ),
        migrations.AddField(
            model_name="richiestapreventivo",
            name="target_content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo di asset a cui è collegato questo record (automezzo, stabilimento, etc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="Tipo Target",
            ),
        ),
        migrations.AddField(
            model_name="richiestapreventivo",
            name="target_object_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID specifico dell'asset target",
                null=True,
                verbose_name="ID Target",
            ),
        ),
    ]
