# Generated by Django 6.0 on 2025-12-26 07:02

from django.db import migrations, models


def update_bozza_to_creato(apps, schema_editor):
    """Converte tutti i record con stato BOZZA in CREATO"""
    RichiestaPreventivo = apps.get_model('preventivi', 'RichiestaPreventivo')
    RichiestaPreventivo.objects.filter(stato='BOZZA').update(stato='CREATO')


class Migration(migrations.Migration):

    dependencies = [
        ('preventivi', '0003_richiestapreventivo_auto_attach_documents_and_more'),
    ]

    operations = [
        # Prima converti i dati esistenti
        migrations.RunPython(update_bozza_to_creato, reverse_code=migrations.RunPython.noop),
        # Poi altera il field con le nuove scelte
        migrations.AlterField(
            model_name='richiestapreventivo',
            name='stato',
            field=models.CharField(choices=[('CREATO', 'Creato'), ('INVIATO_FORNITORI', 'Inviato ai fornitori'), ('PREVENTIVI_RACCOLTI', 'Preventivi raccolti'), ('IN_VALUTAZIONE', 'In valutazione'), ('APPROVATO', 'Approvato'), ('ANNULLATO', 'Annullato')], default='CREATO', max_length=25),
        ),
    ]
