# Generated by Django 4.2.21 on 2025-11-29 14:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome o Ragione Sociale", max_length=200
                    ),
                ),
                ("indirizzo", models.TextField(blank=True)),
                ("citta", models.CharField(blank=True, max_length=100)),
                ("cap", models.CharField(blank=True, max_length=10)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("partita_iva", models.CharField(blank=True, max_length=15)),
                ("codice_fiscale", models.CharField(blank=True, max_length=16)),
                ("codice_univoco", models.CharField(blank=True, max_length=10)),
                ("pec", models.EmailField(blank=True, max_length=254)),
                (
                    "tipo_pagamento",
                    models.CharField(
                        choices=[
                            ("immediato", "Immediato"),
                            ("15_giorni", "15 giorni"),
                            ("30_giorni", "30 giorni"),
                            ("60_giorni", "60 giorni"),
                            ("90_giorni", "90 giorni"),
                            ("120_giorni", "120 giorni"),
                        ],
                        default="immediato",
                        max_length=20,
                    ),
                ),
                (
                    "limite_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Limite di credito concesso (€)",
                        max_digits=10,
                    ),
                ),
                ("zona", models.CharField(blank=True, max_length=100)),
                (
                    "orario_consegna",
                    models.CharField(
                        default="Orari negozio: 9-13 16-19:30",
                        help_text="Orari di consegna e eventuali note specifiche",
                        max_length=200,
                    ),
                ),
                (
                    "giorno_chiusura",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lunedi", "Lunedì"),
                            ("martedi", "Martedì"),
                            ("mercoledi", "Mercoledì"),
                            ("giovedi", "Giovedì"),
                            ("venerdi", "Venerdì"),
                            ("sabato", "Sabato"),
                            ("domenica", "Domenica"),
                        ],
                        help_text="Giorno di chiusura settimanale del cliente",
                        max_length=10,
                    ),
                ),
                ("attivo", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clienti",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Fornitore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome o Ragione Sociale", max_length=200
                    ),
                ),
                ("indirizzo", models.TextField(blank=True)),
                ("citta", models.CharField(blank=True, max_length=100)),
                ("cap", models.CharField(blank=True, max_length=10)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("partita_iva", models.CharField(max_length=15)),
                ("codice_fiscale", models.CharField(blank=True, max_length=16)),
                (
                    "pec",
                    models.EmailField(
                        blank=True,
                        help_text="PEC del fornitore per fatturazione elettronica",
                        max_length=254,
                    ),
                ),
                (
                    "codice_destinatario",
                    models.CharField(
                        blank=True,
                        help_text="Codice destinatario SDI (7 caratteri)",
                        max_length=7,
                    ),
                ),
                ("iban", models.CharField(blank=True, max_length=34)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("materie_prime", "Materie Prime"),
                            ("semilavorati", "Semilavorati"),
                            ("servizi", "Servizi"),
                            ("consulenza", "Consulenza"),
                            ("software", "Software/IT"),
                            ("altri", "Altri"),
                        ],
                        default="altri",
                        max_length=20,
                    ),
                ),
                (
                    "tipo_pagamento",
                    models.CharField(
                        choices=[
                            ("bonifico_30", "Bonifico 30 gg"),
                            ("bonifico_60", "Bonifico 60 gg"),
                            ("bonifico_90", "Bonifico 90 gg"),
                            ("bonifico_120", "Bonifico 120 gg"),
                            ("rid_30", "RID 30 gg"),
                            ("rid_60", "RID 60 gg"),
                            ("riba_30", "RIBA 30 gg"),
                            ("riba_60", "RIBA 60 gg"),
                            ("contrassegno", "Contrassegno"),
                            ("anticipo", "Anticipo 100%"),
                            ("fine_mese", "Fine Mese"),
                            ("immediato", "Pagamento Immediato"),
                        ],
                        default="bonifico_30",
                        max_length=20,
                    ),
                ),
                (
                    "priorita_pagamento_default",
                    models.CharField(
                        choices=[
                            ("critica", "🔴 Critica (Urgente)"),
                            ("alta", "🟡 Alta (Prioritaria)"),
                            ("media", "🔵 Media (Normale)"),
                            ("bassa", "⚪ Bassa (Differibile)"),
                        ],
                        default="media",
                        help_text="Priorità di default per i pagamenti a questo fornitore",
                        max_length=10,
                    ),
                ),
                ("referente_nome", models.CharField(blank=True, max_length=100)),
                ("referente_telefono", models.CharField(blank=True, max_length=20)),
                ("referente_email", models.EmailField(blank=True, max_length=254)),
                ("attivo", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fornitore",
                "verbose_name_plural": "Fornitori",
                "ordering": ["nome"],
            },
        ),
    ]
