# Generated by Django 4.2.21 on 2025-11-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornitore",
            name="partita_iva",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
