# Generated by Django 4.2.21 on 2025-11-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0002_alter_fornitore_partita_iva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornitore",
            name="partita_iva",
            field=models.CharField(max_length=15),
        ),
    ]
