# Generated by Django 4.2.21 on 2025-12-07 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("preventivi", "0002_preventivo_file_preventivo"),
        ("anagrafica", "0003_alter_fornitore_partita_iva"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdineAcquisto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_ordine",
                    models.CharField(
                        help_text="Numero ODA generato automaticamente (ODA-YYYY-NNN)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("data_ordine", models.DateTimeField(auto_now_add=True)),
                (
                    "data_consegna_richiesta",
                    models.DateField(help_text="Data richiesta per la consegna"),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("CREATO", "Creato"),
                            ("RICEVUTO", "Ricevuto"),
                            ("PAGATO", "Pagato"),
                        ],
                        default="CREATO",
                        help_text="Stato attuale dell'ordine",
                        max_length=20,
                    ),
                ),
                (
                    "importo_totale",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Importo totale dell'ordine",
                        max_digits=15,
                    ),
                ),
                ("valuta", models.CharField(default="EUR", max_length=3)),
                (
                    "termini_pagamento",
                    models.CharField(
                        help_text="Condizioni di pagamento", max_length=200
                    ),
                ),
                (
                    "tempi_consegna",
                    models.CharField(
                        help_text="Tempi di consegna previsti", max_length=200
                    ),
                ),
                (
                    "data_ricevimento",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data di ricevimento della merce",
                        null=True,
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateTimeField(
                        blank=True, help_text="Data di pagamento", null=True
                    ),
                ),
                (
                    "note_ordine",
                    models.TextField(blank=True, help_text="Note generali sull'ordine"),
                ),
                (
                    "riferimento_esterno",
                    models.CharField(
                        blank=True,
                        help_text="Riferimento del fornitore",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creato_da",
                    models.ForeignKey(
                        help_text="Utente che ha creato l'ordine",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordini_creati",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fornitore",
                    models.ForeignKey(
                        help_text="Fornitore dell'ordine",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="anagrafica.fornitore",
                    ),
                ),
                (
                    "pagato_da",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utente che ha confermato il pagamento",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordini_pagati",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preventivo_originale",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preventivo che ha generato questo ordine (se applicabile)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="preventivi.preventivo",
                    ),
                ),
                (
                    "ricevuto_da",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utente che ha confermato il ricevimento",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordini_ricevuti",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordine di Acquisto",
                "verbose_name_plural": "Ordini di Acquisto",
                "ordering": ["-data_ordine"],
                "indexes": [
                    models.Index(
                        fields=["numero_ordine"], name="acquisti_or_numero__795c3a_idx"
                    ),
                    models.Index(fields=["stato"], name="acquisti_or_stato_12c5db_idx"),
                    models.Index(
                        fields=["fornitore"], name="acquisti_or_fornito_b17873_idx"
                    ),
                    models.Index(
                        fields=["data_ordine"], name="acquisti_or_data_or_241d7d_idx"
                    ),
                ],
            },
        ),
    ]
