# Generated by Django 4.2.21 on 2025-11-25 03:52

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dipendente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "livello",
                    models.CharField(
                        choices=[
                            ("amministratore", "Amministratore"),
                            ("contabile", "Contabile"),
                            ("operativo", "Operativo"),
                            ("magazziniere", "Magazziniere"),
                            ("rappresentante", "Rappresentante"),
                            ("autista", "Autista"),
                            ("supervisore", "Supervisore"),
                        ],
                        default="operativo",
                        help_text="Determina i permessi di accesso al sistema",
                        max_length=30,
                        verbose_name="Livello autorizzazioni",
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("attivo", "Attivo"),
                            ("sospeso", "Sospeso"),
                            ("dimesso", "Dimesso"),
                            ("prova", "In Prova"),
                        ],
                        default="attivo",
                        help_text="Stato lavorativo attuale",
                        max_length=20,
                        verbose_name="Stato dipendente",
                    ),
                ),
                (
                    "indirizzo",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Indirizzo completo",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        help_text="Numero di telefono principale",
                        max_length=20,
                        null=True,
                        verbose_name="Telefono",
                    ),
                ),
                (
                    "telefono_emergenza",
                    models.CharField(
                        blank=True,
                        help_text="Contatto di emergenza",
                        max_length=20,
                        null=True,
                        verbose_name="Telefono emergenza",
                    ),
                ),
                (
                    "data_nascita",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data di nascita"
                    ),
                ),
                (
                    "data_assunzione",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data di assunzione"
                    ),
                ),
                (
                    "codice_fiscale",
                    models.CharField(
                        blank=True,
                        help_text="Codice fiscale italiano (16 caratteri)",
                        max_length=16,
                        null=True,
                        unique=True,
                        verbose_name="Codice Fiscale",
                    ),
                ),
                (
                    "carta_identita_numero",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Numero carta di identità",
                    ),
                ),
                (
                    "carta_identita_scadenza",
                    models.DateField(
                        blank=True, null=True, verbose_name="Scadenza carta identità"
                    ),
                ),
                (
                    "patente_numero",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Numero patente di guida",
                    ),
                ),
                (
                    "patente_scadenza",
                    models.DateField(
                        blank=True, null=True, verbose_name="Scadenza patente"
                    ),
                ),
                (
                    "patente_categorie",
                    models.CharField(
                        blank=True,
                        help_text="Es: B, C, D, etc.",
                        max_length=20,
                        null=True,
                        verbose_name="Categorie patente",
                    ),
                ),
                (
                    "posizione_inail",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Codice INAIL",
                    ),
                ),
                (
                    "posizione_inps",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Codice INPS"
                    ),
                ),
                (
                    "foto_profilo",
                    models.FileField(
                        blank=True,
                        help_text="Immagine del dipendente (consigliato: 300x300px)",
                        null=True,
                        upload_to="dipendenti/foto/",
                        verbose_name="Foto profilo",
                    ),
                ),
                (
                    "documento_carta_identita",
                    models.FileField(
                        blank=True,
                        help_text="Scansione fronte/retro carta di identità",
                        null=True,
                        upload_to="dipendenti/documenti/ci/",
                        verbose_name="Documento carta identità",
                    ),
                ),
                (
                    "documento_codice_fiscale",
                    models.FileField(
                        blank=True,
                        help_text="Tessera sanitaria o certificato di attribuzione CF",
                        null=True,
                        upload_to="dipendenti/documenti/cf/",
                        verbose_name="Documento codice fiscale",
                    ),
                ),
                (
                    "documento_patente",
                    models.FileField(
                        blank=True,
                        help_text="Scansione fronte/retro patente di guida",
                        null=True,
                        upload_to="dipendenti/documenti/patenti/",
                        verbose_name="Documento patente",
                    ),
                ),
                (
                    "ultimo_accesso",
                    models.DateTimeField(
                        blank=True,
                        help_text="Ultimo login al sistema",
                        null=True,
                        verbose_name="Ultimo accesso",
                    ),
                ),
                (
                    "creato_il",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data creazione"
                    ),
                ),
                (
                    "modificato_il",
                    models.DateTimeField(auto_now=True, verbose_name="Ultima modifica"),
                ),
                (
                    "note_interne",
                    models.TextField(
                        blank=True,
                        help_text="Informazioni riservate al management",
                        null=True,
                        verbose_name="Note interne",
                    ),
                ),
                (
                    "creato_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dipendenti_creati",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creato da",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dipendente",
                "verbose_name_plural": "Dipendenti",
                "ordering": ["last_name", "first_name"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditLogDipendente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "azione",
                    models.CharField(
                        choices=[
                            ("creazione", "Creazione"),
                            ("modifica", "Modifica"),
                            ("eliminazione", "Eliminazione"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("cambio_livello", "Cambio Livello"),
                        ],
                        max_length=20,
                        verbose_name="Tipo azione",
                    ),
                ),
                (
                    "dettagli",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dati delle modifiche in formato JSON",
                        verbose_name="Dettagli modifiche",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data/Ora"
                    ),
                ),
                (
                    "indirizzo_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Indirizzo IP"
                    ),
                ),
                (
                    "dipendente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dipendente",
                    ),
                ),
                (
                    "eseguita_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs_eseguiti",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eseguita da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Audit Dipendente",
                "verbose_name_plural": "Logs Audit Dipendenti",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["dipendente", "-timestamp"],
                        name="dipendenti__dipende_a2e52e_idx",
                    ),
                    models.Index(
                        fields=["azione"], name="dipendenti__azione_db97a5_idx"
                    ),
                    models.Index(
                        fields=["-timestamp"], name="dipendenti__timesta_0049b3_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="dipendente",
            index=models.Index(
                fields=["livello"], name="dipendenti__livello_b2e0c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dipendente",
            index=models.Index(fields=["stato"], name="dipendenti__stato_ce69df_idx"),
        ),
        migrations.AddIndex(
            model_name="dipendente",
            index=models.Index(
                fields=["data_assunzione"], name="dipendenti__data_as_7e7e20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dipendente",
            index=models.Index(
                fields=["ultimo_accesso"], name="dipendenti__ultimo__ac7873_idx"
            ),
        ),
    ]
