# Generated by Django 6.0 on 2025-12-27 07:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Data')),
                ('tipo', models.CharField(choices=[('entrata', 'Entrata'), ('uscita', 'Uscita')], max_length=10, verbose_name='Tipo timbratura')),
                ('orario', models.TimeField(auto_now_add=True, verbose_name='Orario')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp completo')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('latitudine', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitudine')),
                ('longitudine', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitudine')),
                ('indirizzo_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Indirizzo IP')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenze', to=settings.AUTH_USER_MODEL, verbose_name='Dipendente')),
            ],
            options={
                'verbose_name': 'Presenza',
                'verbose_name_plural': 'Presenze',
                'ordering': ['-data', '-orario'],
                'indexes': [models.Index(fields=['dipendente', '-data'], name='dipendenti__dipende_9d56bc_idx'), models.Index(fields=['-data'], name='dipendenti__data_206c3f_idx'), models.Index(fields=['tipo'], name='dipendenti__tipo_16ec6c_idx')],
                'unique_together': {('dipendente', 'data', 'tipo', 'timestamp')},
            },
        ),
    ]
