# Generated by Django 6.0 on 2025-12-27 13:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0002_presenza'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiornataLavorativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Data')),
                ('ore_lavorate', models.DecimalField(decimal_places=2, help_text='Ore totali lavorate nella giornata', max_digits=5, verbose_name='Ore Lavorate')),
                ('ore_straordinari', models.DecimalField(decimal_places=2, default=0, help_text='Ore oltre le 8 ore standard', max_digits=5, verbose_name='Ore Straordinari')),
                ('ore_standard', models.DecimalField(decimal_places=2, default=8.0, help_text='Ore standard per questa giornata', max_digits=5, verbose_name='Ore Standard')),
                ('conclusa', models.BooleanField(default=True, verbose_name='Giornata Conclusa')),
                ('timestamp_conclusione', models.DateTimeField(auto_now_add=True, verbose_name='Data/Ora Conclusione')),
                ('note_conclusione', models.TextField(blank=True, help_text='Note sulla giornata lavorativa', null=True, verbose_name='Note Conclusione')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giornate_lavorative', to=settings.AUTH_USER_MODEL, verbose_name='Dipendente')),
            ],
            options={
                'verbose_name': 'Giornata Lavorativa',
                'verbose_name_plural': 'Giornate Lavorative',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['dipendente', 'data'], name='dipendenti__dipende_cc2bf1_idx'), models.Index(fields=['data'], name='dipendenti__data_187641_idx')],
                'unique_together': {('dipendente', 'data')},
            },
        ),
    ]
