# Generated by Django 4.2.21 on 2025-12-21 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=200, verbose_name="Nome Visualizzato"),
                ),
                (
                    "email_address",
                    models.EmailField(max_length=254, verbose_name="Indirizzo Email"),
                ),
                (
                    "smtp_server",
                    models.CharField(
                        default="smtp.gmail.com",
                        max_length=200,
                        verbose_name="Server SMTP",
                    ),
                ),
                (
                    "smtp_port",
                    models.IntegerField(default=587, verbose_name="Porta SMTP"),
                ),
                (
                    "smtp_username",
                    models.CharField(max_length=200, verbose_name="Username SMTP"),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        help_text="Verrà crittografata automaticamente",
                        max_length=500,
                        verbose_name="Password SMTP",
                    ),
                ),
                ("use_tls", models.BooleanField(default=True, verbose_name="Usa TLS")),
                ("use_ssl", models.BooleanField(default=False, verbose_name="Usa SSL")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Configurazione Attiva"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Email Verificata"),
                ),
                (
                    "last_test_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ultimo Test"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="Ultimo Errore"),
                ),
                (
                    "daily_limit",
                    models.IntegerField(default=500, verbose_name="Limite Giornaliero"),
                ),
                (
                    "hourly_limit",
                    models.IntegerField(default=50, verbose_name="Limite Orario"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mail_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configurazione Email",
                "verbose_name_plural": "Configurazioni Email",
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome Template"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descrizione"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("preventivi", "Preventivi"),
                            ("automezzi", "Automezzi"),
                            ("stabilimenti", "Stabilimenti"),
                            ("acquisti", "Acquisti"),
                            ("fatturazione", "Fatturazione"),
                            ("anagrafica", "Anagrafica"),
                            ("sistema", "Sistema"),
                            ("generico", "Generico"),
                        ],
                        default="generico",
                        max_length=100,
                        verbose_name="Categoria",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Oggetto")),
                ("content_html", models.TextField(verbose_name="Contenuto HTML")),
                (
                    "content_text",
                    models.TextField(blank=True, verbose_name="Contenuto Testuale"),
                ),
                (
                    "available_variables",
                    models.JSONField(
                        default=dict, verbose_name="Variabili Disponibili"
                    ),
                ),
                (
                    "sample_data",
                    models.JSONField(default=dict, verbose_name="Dati Esempio"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Attivo")),
                (
                    "is_system",
                    models.BooleanField(default=False, verbose_name="Template Sistema"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="Utilizzi"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Email",
                "verbose_name_plural": "Template Email",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("to_addresses", models.JSONField(verbose_name="Destinatari")),
                ("cc_addresses", models.JSONField(default=list, verbose_name="CC")),
                ("bcc_addresses", models.JSONField(default=list, verbose_name="BCC")),
                ("subject", models.TextField(verbose_name="Oggetto")),
                (
                    "content_html",
                    models.TextField(blank=True, verbose_name="Contenuto HTML"),
                ),
                (
                    "content_text",
                    models.TextField(blank=True, verbose_name="Contenuto Testuale"),
                ),
                (
                    "has_attachments",
                    models.BooleanField(default=False, verbose_name="Ha Allegati"),
                ),
                (
                    "attachments_info",
                    models.JSONField(default=list, verbose_name="Info Allegati"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In Attesa"),
                            ("sending", "Invio"),
                            ("sent", "Inviato"),
                            ("delivered", "Consegnato"),
                            ("failed", "Fallito"),
                            ("bounced", "Rimbalzato"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "smtp_response",
                    models.TextField(blank=True, verbose_name="Risposta SMTP"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Messaggio Errore"),
                ),
                (
                    "delivery_attempts",
                    models.IntegerField(default=0, verbose_name="Tentativi Consegna"),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "related_description",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Descrizione Collegamento",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inviato il"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Consegnato il"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "sender_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="mail.emailconfiguration",
                    ),
                ),
                (
                    "template_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mail.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Messaggio Email",
                "verbose_name_plural": "Messaggi Email",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Nome File"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="Tipo MIME"),
                ),
                (
                    "size",
                    models.IntegerField(default=0, verbose_name="Dimensione (bytes)"),
                ),
                (
                    "file_path",
                    models.FileField(
                        upload_to="mail_attachments/%Y/%m/", verbose_name="File"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Hash File"
                    ),
                ),
                (
                    "source_app",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="App Origine"
                    ),
                ),
                (
                    "source_info",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Info Origine"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="mail.emailmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allegato Email",
                "verbose_name_plural": "Allegati Email",
                "ordering": ["filename"],
            },
        ),
        migrations.CreateModel(
            name="EmailStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Data"
                    ),
                ),
                (
                    "emails_sent",
                    models.IntegerField(default=0, verbose_name="Email Inviate"),
                ),
                (
                    "emails_failed",
                    models.IntegerField(default=0, verbose_name="Email Fallite"),
                ),
                (
                    "emails_bounced",
                    models.IntegerField(default=0, verbose_name="Email Rimbalzate"),
                ),
                (
                    "preventivi_sent",
                    models.IntegerField(default=0, verbose_name="Preventivi Inviati"),
                ),
                (
                    "automezzi_sent",
                    models.IntegerField(default=0, verbose_name="Automezzi Inviati"),
                ),
                (
                    "acquisti_sent",
                    models.IntegerField(default=0, verbose_name="Acquisti Inviati"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="mail.emailconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistiche Email",
                "verbose_name_plural": "Statistiche Email",
                "ordering": ["-date"],
                "unique_together": {("config", "date")},
            },
        ),
    ]
