# Generated by Django 5.0.8 on 2025-12-24 06:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("mail", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("send", "Invio"),
                            ("receive", "Ricezione"),
                            ("sync", "Sincronizzazione"),
                            ("error", "Errore"),
                            ("config", "Configurazione"),
                        ],
                        max_length=50,
                        verbose_name="Tipo Evento",
                    ),
                ),
                (
                    "event_description",
                    models.TextField(verbose_name="Descrizione Evento"),
                ),
                (
                    "event_data",
                    models.JSONField(default=dict, verbose_name="Dati Evento"),
                ),
                ("success", models.BooleanField(default=True, verbose_name="Successo")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Messaggio Errore"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
            ],
            options={
                "verbose_name": "Log Email",
                "verbose_name_plural": "Log Email",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EmailQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("to_addresses", models.JSONField(verbose_name="Destinatari")),
                ("cc_addresses", models.JSONField(default=list, verbose_name="CC")),
                ("bcc_addresses", models.JSONField(default=list, verbose_name="BCC")),
                ("subject", models.TextField(verbose_name="Oggetto")),
                (
                    "content_html",
                    models.TextField(blank=True, verbose_name="Contenuto HTML"),
                ),
                (
                    "content_text",
                    models.TextField(blank=True, verbose_name="Contenuto Testuale"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Molto Alta"),
                            (2, "Alta"),
                            (3, "Media-Alta"),
                            (4, "Media"),
                            (5, "Media-Bassa"),
                            (6, "Bassa"),
                            (7, "Molto Bassa"),
                        ],
                        default=5,
                        verbose_name="Priorità",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Programmato per",
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(default=3, verbose_name="Tentativi Massimi"),
                ),
                (
                    "attempt_count",
                    models.IntegerField(default=0, verbose_name="Tentativi Effettuati"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In Attesa"),
                            ("processing", "Elaborazione"),
                            ("sent", "Inviato"),
                            ("failed", "Fallito"),
                            ("cancelled", "Annullato"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Messaggio Errore"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inviato il"
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
            ],
            options={
                "verbose_name": "Email in Coda",
                "verbose_name_plural": "Email in Coda",
                "ordering": ["priority", "scheduled_at", "created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="emailmessage",
            options={
                "ordering": ["-sent_at", "-received_at", "-created_at"],
                "verbose_name": "Messaggio Email",
                "verbose_name_plural": "Messaggi Email",
            },
        ),
        migrations.RemoveField(
            model_name="emailmessage",
            name="delivered_at",
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="content_size",
            field=models.IntegerField(default=0, verbose_name="Dimensione (bytes)"),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="direction",
            field=models.CharField(
                choices=[("incoming", "In Arrivo"), ("outgoing", "In Uscita")],
                default="outgoing",
                max_length=10,
                verbose_name="Direzione",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="from_address",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Da"),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="from_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nome Mittente"
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="is_flagged",
            field=models.BooleanField(default=False, verbose_name="Contrassegnato"),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="is_read",
            field=models.BooleanField(default=True, verbose_name="Letto"),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="is_spam",
            field=models.BooleanField(default=False, verbose_name="Spam"),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="message_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Message ID"
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="received_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ricevuto il"
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="reply_to",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Rispondi A"
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="server_uid",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="UID Server"
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="thread_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Thread ID"
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Bozza"),
                    ("pending", "In Attesa"),
                    ("queued", "In Coda"),
                    ("sending", "Invio"),
                    ("sent", "Inviato"),
                    ("delivered", "Consegnato"),
                    ("failed", "Fallito"),
                    ("bounced", "Rimbalzato"),
                    ("received", "Ricevuto"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Stato",
            ),
        ),
        migrations.CreateModel(
            name="EmailFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome Cartella"),
                ),
                (
                    "folder_type",
                    models.CharField(
                        choices=[
                            ("inbox", "Posta in Arrivo"),
                            ("sent", "Posta Inviata"),
                            ("drafts", "Bozze"),
                            ("trash", "Cestino"),
                            ("spam", "Spam"),
                            ("custom", "Personalizzata"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "total_messages",
                    models.IntegerField(default=0, verbose_name="Totale Messaggi"),
                ),
                (
                    "unread_messages",
                    models.IntegerField(default=0, verbose_name="Messaggi Non Letti"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="mail.emailconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cartella Email",
                "verbose_name_plural": "Cartelle Email",
                "ordering": ["config", "folder_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mail.emailfolder",
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["sender_config", "folder"],
                name="mail_emailm_sender__2cdaaa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["message_id"], name="mail_emailm_message_31f09f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["direction", "status"], name="mail_emailm_directi_21db5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="mail_emailm_content_f82f4b_idx",
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="mail.emailconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="mail.emailmessage",
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailqueue",
            name="config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queued_emails",
                to="mail.emailconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="emailqueue",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailfolder",
            unique_together={("config", "name")},
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["config", "event_type"], name="mail_emaill_config__83c75a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["timestamp"], name="mail_emaill_timesta_1daa7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailqueue",
            index=models.Index(
                fields=["status", "scheduled_at"], name="mail_emailq_status_f5622d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailqueue",
            index=models.Index(
                fields=["config", "status"], name="mail_emailq_config__52d97d_idx"
            ),
        ),
    ]
