# Generated by Django 5.0.8 on 2025-12-28 08:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_emaillog_emailqueue_alter_emailmessage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailconfiguration",
            name="imap_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Abilita ricezione IMAP"
            ),
        ),
        migrations.AddField(
            model_name="emailconfiguration",
            name="imap_password",
            field=models.CharField(
                blank=True,
                help_text="Lascia vuoto per usare smtp_password",
                max_length=500,
                verbose_name="Password IMAP",
            ),
        ),
        migrations.AddField(
            model_name="emailconfiguration",
            name="imap_port",
            field=models.IntegerField(default=993, verbose_name="Porta IMAP"),
        ),
        migrations.AddField(
            model_name="emailconfiguration",
            name="imap_server",
            field=models.CharField(
                blank=True,
                default="imap.gmail.com",
                max_length=200,
                verbose_name="Server IMAP",
            ),
        ),
        migrations.AddField(
            model_name="emailconfiguration",
            name="imap_use_ssl",
            field=models.BooleanField(default=True, verbose_name="IMAP usa SSL"),
        ),
        migrations.AddField(
            model_name="emailconfiguration",
            name="imap_use_tls",
            field=models.BooleanField(default=False, verbose_name="IMAP usa TLS"),
        ),
        migrations.AddField(
            model_name="emailconfiguration",
            name="imap_username",
            field=models.CharField(
                blank=True,
                help_text="Lascia vuoto per usare smtp_username",
                max_length=200,
                verbose_name="Username IMAP",
            ),
        ),
        migrations.AddField(
            model_name="emailconfiguration",
            name="last_imap_error",
            field=models.TextField(blank=True, verbose_name="Ultimo errore IMAP"),
        ),
        migrations.AddField(
            model_name="emailconfiguration",
            name="last_imap_sync",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ultima sincronizzazione IMAP"
            ),
        ),
        migrations.CreateModel(
            name="EmailLabel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome Etichetta"),
                ),
                ("slug", models.SlugField(max_length=100, verbose_name="Slug")),
                (
                    "color",
                    models.CharField(
                        default="#4285f4",
                        help_text="Codice colore hex (es. #4285f4)",
                        max_length=7,
                        verbose_name="Colore",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="tag", max_length=50, verbose_name="Icona"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Ordine")),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Visibile"),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Le etichette sistema non possono essere eliminate",
                        verbose_name="Etichetta Sistema",
                    ),
                ),
                (
                    "message_count",
                    models.IntegerField(default=0, verbose_name="Numero Messaggi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="mail.emailconfiguration",
                        verbose_name="Configurazione",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etichetta Email",
                "verbose_name_plural": "Etichette Email",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                related_name="messages",
                to="mail.emaillabel",
                verbose_name="Etichette",
            ),
        ),
        migrations.AddIndex(
            model_name="emaillabel",
            index=models.Index(
                fields=["configuration", "is_visible"],
                name="mail_emaill_configu_928979_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emaillabel",
            unique_together={("configuration", "slug")},
        ),
    ]
